default: &default
  adapter: postgresql
  encoding: unicode
  user: valmy
  password: 12345678
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruptiva_challenge_development
test:
  <<: *default
  database: ruptiva_challenge_test
production:
  <<: *default
  database: ruptiva_challenge_production
  username: ruptiva_challenge
  password: <%= ENV['RUPTIVA_CHALLENGE_DATABASE_PASSWORD'] %>
